/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

/**
 *
 * @author Juan Antonio
 */
public class Game extends javax.swing.JPanel {
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelTitulo;
    //numero de imagenes
    String[] rutasImagenes= new String[5];
    
    //contador
    int contador=0;

    JLabel[] circles = new JLabel[5];

    /**
     * Creates new form Embarque
     */
   public Game(String titulo, String descripcion, String imagen) {
        initComponents();
     // setImageLabel(Boton1, "src/imagenes/PuntoCarruselFilled.png", new Dimension(15,15));
      //setImageLabel(Boton2, "src/imagenes/PuntoCarruselEmpty.png", new Dimension(15,15));
    //     setImageLabel(Boton3, "src/imagenes/PuntoCarruselEmpty.png", new Dimension(15,15));
      //    setImageLabel(Boton4, "src/imagenes/PuntoCarruselEmpty.png", new Dimension(15,15));
        //   setImageLabel(Boton5, "src/imagenes/PuntoCarruselEmpty.png", new Dimension(15,15));
     JPanel titlePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        titlePanel.setOpaque(false); // Hacer que el panel sea transparente
        
        jLabelTitulo = new javax.swing.JLabel();
        if (titulo != null) {
            jLabelTitulo.setText(titulo);
        }
        jLabelTitulo.setForeground(new java.awt.Color(247, 247, 247)); // Color blanco
        jLabelTitulo.setFont(new Font("Raleway", Font.BOLD, 18)); // Fuente Raleway Medium 18 Bold
        titlePanel.add(jLabelTitulo);
        
        bg.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 700, 120));
        
        // Crear un panel para la descripción
        JPanel descriptionPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        descriptionPanel.setOpaque(false); // Hacer que el panel sea transparente
        
        jLabelDescripcion = new javax.swing.JLabel();
        if (descripcion != null) {
            jLabelDescripcion.setText(descripcion);
        }
        jLabelDescripcion.setForeground(new java.awt.Color(247, 247, 247)); // Color blanco
        jLabelDescripcion.setFont(new Font("Raleway", Font.PLAIN, 12)); // Fuente Raleway 12 Plain
        descriptionPanel.add(jLabelDescripcion);
        
        for (int i = 0; i < rutasImagenes.length; i++) {
           rutasImagenes[i]= "src/imagenes/"+imagen+i+".png";
       }
        
        bg.add(descriptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 650, 700, 120));
        
        setImageLabel(jLabel3, "src/imagenes/Comenzar.png", new Dimension(253,44));
       
           
            
        
            initCircles();
              Embarque0.setIcon(new ImageIcon(rutasImagenes[contador]));
   
        
           updateCircles();
           
           
    }

       
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CuadradoFondo = new javax.swing.JLabel();
        Embarque0 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        FondoIzquierda = new javax.swing.JLabel();
        FondoDerecha = new javax.swing.JLabel();
        FlechaIzquierda = new javax.swing.JLabel();
        FlechaDerecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(CuadradoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 790, 200));

        Embarque0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Embarque0.png"))); // NOI18N
        add(Embarque0, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 910, 490));

        bg.setOpaque(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuadrado fondo enfocado.png"))); // NOI18N
        bg.add(FondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 150, 420));

        FondoDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuadrado fondo enfocado.png"))); // NOI18N
        FondoDerecha.setText("jLabel1");
        bg.add(FondoDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 770, -1));

        FlechaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flecha izquierda.png"))); // NOI18N
        FlechaIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlechaIzquierdaMouseClicked(evt);
            }
        });
        bg.add(FlechaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        FlechaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flecha derecha.png"))); // NOI18N
        FlechaDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlechaDerechaMouseClicked(evt);
            }
        });
        bg.add(FlechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barrita aislada descripción.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Comenzar.png"))); // NOI18N
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 680, -1, 50));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1550, 840));
    }// </editor-fold>//GEN-END:initComponents

      private void initCircles() {
        // Crear un panel para los círculos
        JPanel circlePanel = new JPanel(new FlowLayout());
        circlePanel.setOpaque(false); // Hacer que el panel sea transparente
        circlePanel.setPreferredSize(new Dimension(150, 50));
        
        // Crear los JLabels para los círculos
        for (int i = 0; i < rutasImagenes.length; i++) {
            circles[i] = new JLabel();
            circles[i].setIcon(new ImageIcon(getClass().getResource("/imagenes/PuntoCarruselEmpty.png"))); // Imagen de un círculo
            circles[i].setOpaque(false); // Hacer que el JLabel sea transparente
            circles[i].setVisible(true);
            circlePanel.add(circles[i]);
        }
         bg.add(circlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 150, 50));
    
      }
    
    private void FlechaIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaIzquierdaMouseClicked
 contador--;
    if (contador < 0) {
        contador = rutasImagenes.length - 1; // Reiniciar al final del array
    }
    Embarque0.setIcon(new ImageIcon(rutasImagenes[contador]));
    updateCircles();
    }//GEN-LAST:event_FlechaIzquierdaMouseClicked

    private void FlechaDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaDerechaMouseClicked
   contador++;
    if (contador >= rutasImagenes.length) {
        contador = 0; // Reiniciar al principio del array
    }
    Embarque0.setIcon(new ImageIcon(rutasImagenes[contador]));
    updateCircles();
    }//GEN-LAST:event_FlechaDerechaMouseClicked

       private void updateCircles() {
        for (int i = 0; i < circles.length; i++) {
            if (i == contador) {
                circles[i].setIcon(new ImageIcon(getClass().getResource("/imagenes/PuntoCarruselFilled.png")));
            } else {
                circles[i].setIcon(new ImageIcon(getClass().getResource("/imagenes/PuntoCarruselEmpty.png")));
            }
        }
    }
      private void setImageLabel(JLabel labelName, String root, Dimension dimension){
     ImageIcon image= new ImageIcon(root);
     Icon icon = new ImageIcon(
     image.getImage().getScaledInstance(dimension.width, dimension.height, Image.SCALE_DEFAULT));
     labelName.setIcon(icon);
     this.repaint();
 }
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CuadradoFondo;
    private javax.swing.JLabel Embarque0;
    private javax.swing.JLabel FlechaDerecha;
    private javax.swing.JLabel FlechaIzquierda;
    private javax.swing.JLabel FondoDerecha;
    private javax.swing.JLabel FondoIzquierda;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

